In [119]:
import time
import numpy as np
import torch
from torch.autograd import Variable
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset
from torch import nn
import torch.nn.functional as F
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [120]:
X_np = np.array([[[1, 1, 1, 1, 1, 2],
                 [1, 2, 3, 4, 0, 0],
                 [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [1, 2, 3, 4, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [1, 2, 3, 4, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [1, 2, 3, 4, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 4, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 4, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 6, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 6, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 6, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 6, 0, 0],
                [1, 1, 1, 1, 0, 0]],
               
                [[1, 1, 1, 1, 1, 2],
                [1, 3, 2, 3, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [1, 3, 2, 3, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [1, 3, 2, 3, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [1, 3, 2, 3, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 3, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 1, 2],
                [2, 1, 3, 3, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [2, 1, 3, 3, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [2, 1, 3, 3, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [2, 1, 3, 3, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [2, 1, 3, 3, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -4, -2, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -4, -9, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -4, -2, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -4, -2, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -4, -3, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -4, -3, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -6, -5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -6, -5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -6, -5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-2, -3, -6, -5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-3, -2, -6, -5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-3, -2, -6, -5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-3, -2, -6, -5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-3, -2, -6, -5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-3, -2, -6, -11, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 1, 1, 2, 2],
                [-3, -2, -6, -11, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [-3, -2, -6, -11, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [2, 1, 3, 4, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [2, 1, 3, 4, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [2, 1, 3, 4, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 1, 2, 5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 1, 2, 5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 1, 2, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 1, 2, 5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [1, 2, 3, 3, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [1, 2, 3, 3, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 4, 1, 5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 4, 1, 5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 4, 1, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [3, 4, 1, 5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [4, 3, 5, 7, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [4, 3, 5, 7, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [4, 3, 5, 7, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [4, 3, 5, 7, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [2, 3, 1, 6, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 1, 2],
                [2, 3, 1, 6, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 3, 1, 6, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 3, 1, 6, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 3, 1, 6, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 3, 1, 6, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [1, 3, 2, 3, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [1, 3, 2, 3, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [1, 3, 2, 3, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [1, 3, 2, 3, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [1, 3, 2, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [1, 3, 2, 5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 1, 3, 5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 1, 3, 5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 1, 3, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [2, 1, 3, 5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [-2, -3, -4, -5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [-2, -3, -4, -5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [-2, -3, -4, -5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [-2, -3, -4, -5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [-3, -2, -1, -6, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[1, 1, 2, 1, 2, 2],
                [-3, -2, -1, -6, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [-3, -2, -1, -6, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [-3, -2, -1, -6, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [3, 2, 1, 3, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [3, 2, 1, 3, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [3, 2, 1, 3, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [3, 2, 1, 3, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [2, 3, 1, 5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [2, 3, 1, 5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [2, 3, 1, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [2, 3, 1, 5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [1, 3, 2, 5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [1, 3, 2, 5, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [1, 3, 2, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [1, 3, 2, 5, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [1, 2, 3, 6, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [1, 2, 3, 6, 0, 0],
                [0, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [1, 2, 3, 6, 0, 0],
                [1, 0, 1, 1, 0, 0]],
                 
                [[2, 1, 1, 1, 1, 2],
                [1, 2, 3, 6, 0, 0],
                [1, 1, 1, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [3, 2, 1, 5, 0, 0],
                [1, 1, 0, 1, 0, 0]],
                
                [[2, 1, 1, 1, 1, 2],
                [3, 2, 1, 5, 0, 0],
                [1, 0, 1, 1, 0, 0]]])

y_np = np.array([[3],
                [3],
                [3],
                [3],
                [3],
                [3],
                [5],
                [5],
                [5],
                [5],
                [7],
                [7],
                [7],
                [7],
                [2],
                [2],
                [3],
                [2],
                [3],
                [1],
                [5],
                [1],
                [1],
                [1],
                [4],
                [1],
                [4],
                [4],
                [4],
                [4],
                [4],
                [2],
                [4],
                [4],
                [4],
                [2],
                [4],
                [4],
                [4],
                [4],
                [4],
                [5],
                [5],
                [5],
                [5],
                [5],
                [5],
                [5],
                [6],
                [1],
                [6],
                [6],
                [6],
                [6],
                [6],
                [6],
                [6],
                [6],
                [7],
                [7],
                [7],
                [7],
                [7],
                [7],
                [2],
                [2],
                [6],
                [2],
                [3],
                [3],
                [5],
                [5],
                [5],
                [5],
                [4],
                [2],
                [4],
                [4],
                [4],
                [4],
                [4],
                [1],
                [4],
                [5],
                [4],
                [4],
                [6],
                [6],
                [6],
                [6],
                [3],
                [3],
                [3],
                [3],
                [7],
                [7],
                [7],
                [7],
                [6],
                [6]])


In [121]:
print "X_np's pre-expansion shape: {}".format(X_np.shape)
print "y_np shape: {}".format(y_np.shape)

X_np = np.expand_dims(X_np, axis = 1)
print "X_np's shape after adding an extra dimension to conform it to have 4 dimensions: {}".format(X_np.shape)

X_np's pre-expansion shape: (100, 3, 6)
y_np shape: (100, 1)
X_np's shape after adding an extra dimension to conform it to have 4 dimensions: (100, 1, 3, 6)


In [122]:
def multi_class_format(numpy_array):
    new = []
    for item in y_np:
        for i in item:
            new.append(i)
    
    class_labels = []
    
    for i in new:
        identifier = i-1
        class_labels.append(identifier)
        
    return class_labels

Y_array = multi_class_format(y_np)
print Y_array[:25]

[2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 6, 6, 6, 6, 1, 1, 2, 1, 2, 0, 4, 0, 0, 0, 3]


In [123]:
nb_classes = 7 #Total number of classes an LP can belong to

#Function to convert the output label vector into one hot format
def get_one_hot(targets, nb_classes):
    return np.eye(nb_classes)[np.array(targets).reshape(-1)]

In [124]:
y_one_hot = get_one_hot(Y_array, 7)
print "Output shape: {} ".format(y_one_hot.shape)
print y_one_hot

Output shape: (100, 7) 
[[ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  1.  0.  

In [125]:
# Make a train/test split using 20% test size
X_train, X_test, y_train, y_test = train_test_split(X_np, y_one_hot, test_size=0.20, shuffle = True)
print "X_train: {}, y_train: {} , X_test: {} , y_test: {} ".format(X_train.shape[0], y_train.shape[0], X_test.shape[0], y_test.shape[0])

X_train: 80, y_train: 80 , X_test: 20 , y_test: 20 


In [126]:
X_train = torch.from_numpy(X_train).type(torch.FloatTensor)
y_train = torch.from_numpy(y_train).type(torch.LongTensor)

X_test = torch.from_numpy(X_test).type(torch.FloatTensor)
y_test = torch.from_numpy(y_test).type(torch.LongTensor)

print "Training set shape: {} ".format(X_train.size())
print "Training labels shape: {} ".format(y_train.size())

print "Test set shape: {} ".format(X_test.size())
print "Test labels shape: {} ".format(y_test.size())

Training set shape: torch.Size([80, 1, 3, 6]) 
Training labels shape: torch.Size([80, 7]) 
Test set shape: torch.Size([20, 1, 3, 6]) 
Test labels shape: torch.Size([20, 7]) 


In [127]:
#Class for CNN with 3 filters of size 3 each
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels = 1, out_channels = 3, kernel_size=3, stride = 1, padding = 1, dilation = 1, bias = True),
            nn.ReLU())
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels = 3, out_channels = 3, kernel_size=3, stride = 1, padding = 1, dilation = 1, bias = True),
            nn.ReLU())
        self.fc = nn.Linear(6*3*3, 7)
        
    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        return out

#Class for CNN with 2 filters of size 3 each
class CNN2(nn.Module):
    def __init__(self):
        super(CNN2, self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels = 1, out_channels = 2, kernel_size=3, stride = 1, padding = 1, dilation = 1, bias = True),
            nn.ReLU())
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels = 2, out_channels = 2, kernel_size=3, stride = 1, padding = 1, dilation = 1, bias = True),
            nn.ReLU())
        self.fc = nn.Linear(6*3*2, 7)
        
    def forward(self, x):
        out = self.layer1(x)
        out = self.layer2(out)
        out = out.view(out.size(0), -1)
        out = self.fc(out)
        return out

In [128]:
cnn = CNN2()
print cnn

CNN2(
  (layer1): Sequential(
    (0): Conv2d (1, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
  )
  (layer2): Sequential(
    (0): Conv2d (2, 2, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU()
  )
  (fc): Linear(in_features=36, out_features=7)
)


In [129]:
#Converting the training one hot vector labels into indices because PyTorch does not take one-hot vectors
targetnp = y_train.numpy()
idxs = np.where(targetnp > 0)[1]
new_targets = torch.LongTensor(idxs)

In [130]:
#Converting the test one hot vector labels into indices
test_targetnp = y_test.numpy()
test_idxs = np.where(test_targetnp > 0)[1]
new_test_targets = torch.LongTensor(test_idxs)

In [131]:
# create a Adam optimizer
learning_rate = 1e-3
optimizer = torch.optim.Adam(cnn.parameters(), lr=learning_rate, weight_decay = 0)
# create a loss function
loss_func = nn.CrossEntropyLoss()

In [132]:
# run the main training loop
epochs = 1000
train_loss = 0
train_correct = 0
test_correct = 0
for epoch in range(epochs):
        data, target = Variable(X_train), Variable(new_targets)
        optimizer.zero_grad()
        net_out = cnn(data)
        #print net_out
        #print target.data
        
        #sum up the loss
        train_loss = loss_func(net_out, target)
        pred = net_out.data.max(1)[1] #get the index of the max log probabitlity
        train_correct = pred.eq(target.data).sum()
        
        train_loss.backward()
        optimizer.step()
        if epoch % 10 == 0:
            print('\nTraining Epoch: {} Average loss: {:.4f}, Training Accuracy: {}/{} ({:.4f}%)\n'.format(
        epoch, train_loss.data[0], train_correct, len(target),
        100. * train_correct / len(target)))



Training Epoch: 0 Average loss: 1.9873, Training Accuracy: 4/80 (5.0000%)


Training Epoch: 10 Average loss: 1.9490, Training Accuracy: 15/80 (18.7500%)


Training Epoch: 20 Average loss: 1.9134, Training Accuracy: 24/80 (30.0000%)


Training Epoch: 30 Average loss: 1.8718, Training Accuracy: 26/80 (32.5000%)


Training Epoch: 40 Average loss: 1.8202, Training Accuracy: 34/80 (42.5000%)


Training Epoch: 50 Average loss: 1.7572, Training Accuracy: 27/80 (33.7500%)


Training Epoch: 60 Average loss: 1.6823, Training Accuracy: 32/80 (40.0000%)


Training Epoch: 70 Average loss: 1.5983, Training Accuracy: 43/80 (53.7500%)


Training Epoch: 80 Average loss: 1.5123, Training Accuracy: 41/80 (51.2500%)


Training Epoch: 90 Average loss: 1.4377, Training Accuracy: 43/80 (53.7500%)


Training Epoch: 100 Average loss: 1.3783, Training Accuracy: 44/80 (55.0000%)


Training Epoch: 110 Average loss: 1.3261, Training Accuracy: 44/80 (55.0000%)


Training Epoch: 120 Average loss: 1.2769, Training A

In [133]:
test_loss = 0
test_correct = 0

#Converting test data and target labels into pyTorch variables
test_data, test_target = Variable(X_test), Variable(new_test_targets)

tic = time.time()
#Test set output
net_out = cnn(test_data)

test_loss = loss_func(net_out, test_target)
test_pred = net_out.data.max(1)[1] #get the index of max log probability
test_correct = test_pred.eq(test_target.data).sum()

toc = time.time()
time_diff = toc - tic

print('\nTest loss: {:.4f}, Test accuracy: {}/{} ({:.4f}%)\n'.format(
    test_loss.data[0], test_correct, len(test_target), 100. * test_correct / len(test_target)))

print "Time taken to detect: ", time_diff


Test loss: 1.7864, Test accuracy: 15/20 (75.0000%)

Time taken to detect:  0.000709056854248
